### ISSUE TITLE
8851, 8852 - Not getting logs when changing Schema settings in a post

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-yoast-seo#103]
8851 Changed the Page type in the Schema settings
8852 Changed the Article type in the Schema settings

**Comment by DannyWPWS** [comment]
@jwjsystem Please confirm if this is still an issue for you using the current develop etc im not seeing a problem when testing

![image](https://user-images.githubusercontent.com/59394454/201167096-c803cd79-1fdd-49d5-a8b0-6d7954cd72a6.png)

**Comment by robert81** [comment]
false alarm
