### ISSUE TITLE
8807 - changing focus keywords for page/post not triggering log

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-yoast-seo#104]
![w](https://user-images.githubusercontent.com/92275653/200311688-cfef49da-03b9-4bfa-8a74-9fad9ec3125c.png)

I tried to generate logs for changing the focus phrase of both post and page from the yoast metabox and recived a 2XXX Syste Log, instead of a Yoast related log. (8807)

**Comment by DannyWPWS** [comment]
@jwjsystem Not seeing the issue here currently 

![image](https://user-images.githubusercontent.com/59394454/201166612-c0317acd-264d-4255-af7b-e3787df31982.png)

Are you still able to produce this?

**Comment by robert81** [comment]
false alarm
