### ISSUE TITLE
8806 - not triggering log when changing canonical URL of a page/post.

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-yoast-seo#105]

**Comment by DannyWPWS** [comment]
@jwjsystem Iv checked and this seems to be working

![image](https://user-images.githubusercontent.com/59394454/201161287-d8b96d71-fea0-40ff-a422-421f7544b92d.png)

Can you please check again but bare this in mind:

When you edit the URL, if you just type something random into the field like 'sdasdas' and hit save/update post - the page will LOOK like its updated and the info is saved but if you refresh, that random text you added is gone

Unless you supply a well formatted URL https://yoast.com/help/canonical-urls-in-yoast-seo/#utm_source=yoast-seo&utm_medium=software&utm_term=canonical-url&utm_content=advanced-tab the field wont change (and from our codes POV is simply 'false' so when testing be sure to pop a full URL in etc and let me know how you get on
