### ISSUE TITLE
New ID suggestion - post title Slug

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-yoast-seo#108]
Right now when trying to edit a slug of a post title, WSAL reports ID 2017 event. (changed URL of a post).

This would be rather changed to something Yoast related maybe?
![1](https://user-images.githubusercontent.com/92275653/202685150-bc3f96bc-d614-4568-8762-738bbe2130ae.png)

**Comment by robert81** [comment]
The slug is actually a change of URL, so this is working as it should be.
