### ISSUE TITLE
ID 8806 not being reported

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-yoast-seo#110]
8806 - Editing a post, ,Canonical URL change not reported. I have tested this along with Yoast alpha version (see below) their new upcoming release.

https://prnt.sc/_Oq8z1V-v8CX

In case you need the Alpha version of yoast (future update), please find them attached

**Comment by sdobreff** [comment]
That is correct for the time of testing - because then we didnt have the working version of yoast event monitoring - the new yoast version wasnt supported - not the case anymore.
