### ISSUE TITLE
13435 Fatal error: Uncaught TypeError: trim()

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/activity-log-yoast-seo#115]
We have a user reporting the following - can we take a look into or create a patch for him?

_"We have a custom user role on our sites that hides access to the Yoast plugin menus and metaboxes, and we're finding that in version 1.3.1 of WP Activity Log for Yoast SEO, when users are trying to update posts and pages they're getting a fatal error.

It seems like some yoast seo meta may be being set as NULL when the page/post is saved by a user who doesn't have access to the yoast metabox."_

If the seo title is already in the database as NULL (i.e. we haven't set a custom SEO title) the save will happen successfully. If the seo title is not NULL, then we get the below error:

Rolling back to version 1.3.0 fixes the issue.

Sys info [sys.txt](https://github.com/wpwhitesecurity/activity-log-yoast-seo/files/11796242/sys.txt)

`Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php:273 Stack trace: #0 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php(273): trim(NULL) #1 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php(242): WSAL\Plugin_Sensors\Yoast_SEO_Sensor::check_title_change(NULL) #2 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php(127): WSAL\Plugin_Sensors\Yoast_SEO_Sensor::check_seo_data_change() #3 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-includes\class-wp-hook.php(308): WSAL\Plugin_Sensors\Yoast_SEO_Sensor::event_admin_init('') #4 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-includes\class-wp-hook.php(332): WP in C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php on line 273
`

**Comment by sdobreff** [comment]
Ask the user to try this one:
[20230621-activity-log-wp-seo.zip](https://github.com/wpwhitesecurity/activity-log-yoast-seo/files/11813974/20230621-activity-log-wp-seo.zip)

**Comment by jwjsystem** [comment]
@sdobreff 

They are still getting the error message:

`Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php:274 Stack trace: #0 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php(274): trim(NULL) #1 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php(242): WSAL\Plugin_Sensors\Yoast_SEO_Sensor::check_title_change(NULL) #2 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php(127): WSAL\Plugin_Sensors\Yoast_SEO_Sensor::check_seo_data_change() #3 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-includes\class-wp-hook.php(308): WSAL\Plugin_Sensors\Yoast_SEO_Sensor::event_admin_init('') #4 C:\Repos\Clients\the-lyall-hotel-and-spa\wp-includes\class-wp-hook.php(332): WP in C:\Repos\Clients\the-lyall-hotel-and-spa\wp-content\plugins\activity-log-wp-seo\wp-security-audit-log\sensors\class-yoast-seo-sensor.php `on line 274

**Comment by sdobreff** [comment]
Thats good at least we have something different now.
Ask them to try with this one:
[20230622-activity-log-wp-seo.zip](https://github.com/wpwhitesecurity/activity-log-yoast-seo/files/11829863/20230622-activity-log-wp-seo.zip)

**Comment by jwjsystem** [comment]
User confirmed the patch is working! Thank you!
