### ISSUE TITLE
Add event ID 8849 for integrations

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/activity-log-yoast-seo#76]
Let's created event ID 8849 to monitor the status of the integrations found on this page: /wp-admin/admin.php?page=wpseo_dashboard#top#integrations

Event details in the [events ID list](https://docs.google.com/spreadsheets/d/1xjO3E7GtsOMPHTfLyaurNeJqmJkRCRsleBSAhsicyXA/edit#gid=1446535160)

**Comment by DannyWPWS** [comment]
Iv realised we actually already have event 8820 specifically for the "Ryte Integration" found on this "/wp-admin/admin.php?page=wpseo_dashboard#top#integrations" so it doesnt make sense to add an additon event code to cover the 4 other integrations found on the same page

**Comment by robert81** [comment]
Functionality is good but the text is wrong:

![image](https://user-images.githubusercontent.com/3965050/158670899-f0d7b4e6-13c9-4194-8756-803674d34992.png)

The text should be:

Changed the status of the **%integration%** integration.
