### ISSUE TITLE
Event ID 8850 reported after changing the content of a page

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/activity-log-yoast-seo#94]
When I change the content of a page, the plugin also reports event ID 8850 - 

![image](https://user-images.githubusercontent.com/3965050/159919053-00f5a0aa-58c2-4967-9b8d-e7976e0e5d19.png)

**Comment by DannyWPWS** [comment]
This was actually mildly interesting, at some point an empty string has been treated like a bool which was causing the change to always be detected
