### ISSUE TITLE
8820 - Plugin reports "null" instead of integration name

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-yoast-seo#97]
![image](https://user-images.githubusercontent.com/59394454/160130961-5cddb59c-c14a-4087-985d-58055cb2864f.png)

**Comment by martinkrcho** [comment]
@DannyWPWS , this reminds me of https://github.com/wpwhitesecurity/wp-security-audit-log-premium/issues/2489.

Did you see [my comment](https://github.com/wpwhitesecurity/wp-security-audit-log-premium/pull/2491#issue-1176266370) in the PR?

**Comment by DannyWPWS** [comment]
Nothing that interesting sadly, just using the wrong var name I think here :)
